name: build

on:
  push:
    branches: [ add/workflows ]
  pull_request:
    branches: [ add/workflows ]

steps:
- uses: actions/checkout@main
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1.x' 
- run: dotnet build Drive\ Scan