name: build

on:
  push:
    branches: [ add/workflows ]
  pull_request:
    branches: [ add/workflows ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dotnet: [ "3.1.x" ]
    name: Dotnet ${{ matrix.dotnet }} Build
    steps:
      - uses: actions/checkout@main
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build Drive\ Scan